### ISSUE TITLE
booleanValid

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#131] opened 2022-09-05 06:37 UTC

**Comment by lukas-h** [comment] 2022-09-05 06:48
Duplicate of #129

**Closed by lukas-h** 2022-09-05 06:48 UTC

**Comment by armantorkzaban** [comment] 2022-09-07 12:52
Dealt with [here](https://github.com/dartclub/turf_dart/commit/775f0eee9470364185ac8d224372699d08786d41)
